version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run: npm run deploy
workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy:
          filters:
              branches:
                only: master