version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:10.0.0
    steps:
      - checkout
      - run: npm install
      - run: git config --global user.email circleci@deploy.com
      - run: git config --global user.name circleci
      - run: npm run deploy
workflows:
  version: 2
  deploy_workflow:
    jobs:
      - deploy:
          filters:
              branches:
                only: master